DOMAIN = "zaragoza_tram"
API_URL = "https://www.zaragoza.es/sede/servicio/urbanismo-infraestructuras/transporte-urbano/parada-tranvia.json"
PARADAS = [
    ('101', 'AVENIDA DE LA ACADEMIA - Dir: MAGO DE OZ'), ('102', 'AVENIDA DE LA ACADEMIA - Dir: AVENIDA DE LA ACADEMIA'), ('301', 'JUSLIBOL - Dir: MAGO DE OZ'), 
    ('302', 'JUSLIBOL - Dir: AVENIDA DE LA ACADEMIA'), ('201', 'PARQUE GOYA - Dir: MAGO DE OZ'), ('202', 'PARQUE GOYA - Dir: AVENIDA DE LA ACADEMIA'), ('602', 'ADOLFO AZNAR - Dir: AVENIDA DE LA ACADEMIA'), 
    ('501', 'MARGARITA XIRGU - Dir: MAGO DE OZ'), ('502', 'GARCIA ABRIL - Dir: AVENIDA DE LA ACADEMIA'), ('401', 'CAMPUS RIO EBRO - Dir: MAGO DE OZ'), 
    ('402', 'CAMPUS RIO EBRO - Dir: AVENIDA DE LA ACADEMIA'), ('802', 'LEON FELIPE - Dir: AVENIDA DE LA ACADEMIA'), ('701', 'CLARA CAMPOAMOR - Dir: MAGO DE OZ'), 
    ('702', 'PABLO NERUDA - Dir: AVENIDA DE LA ACADEMIA'), ('601', 'LEGAZ LACAMBRA - Dir: MAGO DE OZ'), ('1001', 'LA CHIMENEA Dir: MAGO DE OZ'), 
    ('1002', 'LA CHIMENEA - Dir: AVENIDA DE LA ACADEMIA'), ('901', 'MARTINEZ SORIA - Dir: MAGO DE OZ'), ('902', 'MARIA MONTESSORI - Dir: AVENIDA DE LA ACADEMIA'), 
    ('801', 'ROSALIA DE CASTRO - Dir: MAGO DE OZ'), ('1201', 'CESAR AUGUSTO - Dir: MAGO DE OZ'), ('1202', 'CESAR AUGUSTO - Dir: AVENIDA DE LA ACADEMIA'), 
    ('1101', 'PLAZA DEL PILAR - MURALLAS - Dir: MAGO DE OZ'), ('1102', 'PLAZA DEL PILAR - MURALLAS - Dir: AVENIDA DE LA ACADEMIA'), 
    ('1311', 'PLAZA ARAGON - Dir: MAGO DE OZ'), ('1312', 'PLAZA ARAGON - Dir: AVENIDA DE LA ACADEMIA'), ('1301', 'PLAZA ESPANA - Dir: MAGO DE OZ'), 
    ('1302', 'PLAZA ESPANA - Dir: AVENIDA DE LA ACADEMIA'), ('2101', 'PASEO DE LOS OLVIDADOS - Dir: MAGO DE OZ'), ('2301', 'LOS PAJAROS - Dir: MAGO DE OZ'), 
    ('2401', 'CANTANDO BAJO LA LLUVIA - Dir: MAGO DE OZ'), ('2501', 'MAGO DE OZ - Dir: MAGO DE OZ'), ('1701', 'EMPERADOR CARLOS V - Dir: MAGO DE OZ'), 
    ('1801', 'ROMAREDA - Dir: MAGO DE OZ'), ('1901', 'CASABLANCA - Dir: MAGO DE OZ'), ('2001', 'ARGUALAS - Dir: MAGO DE OZ'), ('2502', 'MAGO DE OZ - Dir: AVENIDA DE LA ACADEMIA'), 
    ('1401', 'GRAN VIA - Dir: MAGO DE OZ'), ('1501', 'FERNANDO EL CATOLICO - GOYA - Dir: MAGO DE OZ'), ('1601', 'PLAZA SAN FRANCISCO - Dir: MAGO DE OZ'), 
    ('1802', 'ROMAREDA - Dir: AVENIDA DE LA ACADEMIA'), ('1902', 'CASABLANCA - Dir: AVENIDA DE LA ACADEMIA'), ('2002', 'ARGUALAS - Dir: AVENIDA DE LA ACADEMIA'), ('2422', 'UN AMERICANO EN PARIS - Dir: AVENIDA DE LA ACADEMIA'), 
    ('1602', 'PLAZA SAN FRANCISCO - Dir: AVENIDA DE LA ACADEMIA'), ('1702', 'EMPERADOR CARLOS V - Dir: AVENIDA DE LA ACADEMIA'), ('1402', 'GRAN VIA - Dir: AVENIDA DE LA ACADEMIA'), 
    ('1502', 'FERNANDO EL CATOLICO - GOYA - Dir: AVENIDA DE LA ACADEMIA'), ('2322', 'LA VENTANA INDISCRETA - Dir: AVENIDA DE LA ACADEMIA'), 
    ('2102', 'PASEO DE LOS OLVIDADOS - Dir: AVENIDA DE LA ACADEMIA')
]